"""Alembic environment: runs migrations over an async connection as the MIGRATION role.

Two rules this file enforces (ADR 011):

* The privileged URL comes only from ``MIGRATION_DATABASE_URL``: the process environment first,
  then the separate git-ignored ``.env.migration`` file (local convenience). It is deliberately not
  part of the application's ``Settings``, so the API and worker cannot read it. It is never printed.
* There is no offline (SQL-script) mode, because it would need the URL just to render text.
"""

import asyncio
import os
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from dotenv import dotenv_values
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

config = context.config

# Tests run Alembic inside the pytest process and switch this off so they do not reconfigure the
# process-wide logging that other tests rely on.
if config.config_file_name is not None and config.attributes.get("configure_logger", True):
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# No SQLAlchemy models exist yet, and migrations are written by hand (not autogenerated).
target_metadata = None


def migration_url() -> str:
    url = os.environ.get("MIGRATION_DATABASE_URL")
    if not url:
        relative = config.get_main_option("migration_env_file")
        if relative and config.config_file_name:
            env_file = Path(config.config_file_name).resolve().parent / relative
            if env_file.is_file():
                url = dotenv_values(env_file).get("MIGRATION_DATABASE_URL")
    if not url:
        # The message names the variable, never a value.
        raise RuntimeError(
            "MIGRATION_DATABASE_URL is not set. Export it, or put it in .env.migration "
            "(postgresql+asyncpg://<migration role>@<host>/<database>)."
        )
    return url


def run_migrations(connection: Connection) -> None:
    # PostgreSQL supports transactional DDL: each upgrade or downgrade is all-or-nothing.
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    # NullPool: a migration is one short job, so it needs one connection and no pool.
    engine = create_async_engine(migration_url(), poolclass=pool.NullPool)
    try:
        async with engine.connect() as connection:
            await connection.run_sync(run_migrations)
    finally:
        await engine.dispose()


if context.is_offline_mode():
    raise RuntimeError("Offline (--sql) mode is not supported; run against a database.")

asyncio.run(run_async_migrations())
